component_depth: 1
languages:
- script
exclude:
- ./bin/.*
- ./bin/com/.*
- ./bin/com/finalist/.*
- ./bin/com/finalist/jag/.*
- ./bin/com/finalist/jag/skelet/.*
- ./bin/com/finalist/jag/taglib/.*
- ./bin/com/finalist/jag/taglib/util/.*
- ./bin/com/finalist/jag/template/.*
- ./bin/com/finalist/jag/template/parser/.*
- ./bin/com/finalist/jag/uml/.*
- ./bin/com/finalist/jag/util/.*
- ./bin/com/finalist/jaggenerator/.*
- ./bin/com/finalist/jaggenerator/menu/.*
- ./bin/com/finalist/jaggenerator/modules/.*
- ./bin/com/finalist/jaggenerator/template/.*
- ./bin/com/finalist/jaggenerator/validation/.*
- ./bin/com/finalist/util/.*
- ./bin/com/finalist/util/log/.*
- ./bin/com/lowagie/.*
- ./bin/com/lowagie/text/.*
- ./bin/com/lowagie/text/html/.*
- ./bin/org/.*
- ./bin/org/netbeans/.*
- ./bin/org/netbeans/lib/.*
- ./bin/org/netbeans/lib/awtextra/.*
- ./conf/.*
- ./doc/.*
- ./doc/docbook/.*
- ./doc/docbook/css/.*
- ./doc/docbook/images/.*
- ./doc/help/.*
- ./doc/help/images/.*
- ./images/.*
- ./lib/.*
- ./templates/.*
- ./templates/entity_facade_jboss_jsk_2_0/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/conf-general/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/conf-general/jmeter/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/conf-struts/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/conf-struts/WEB-INF/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/conf-swing/.*
- ./templates/entity_facade_jboss_jsk_2_0/conf/conf-tapestry/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/config/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/config/ant/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/config/jboss/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/config/jmeter/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/config/maven/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/config/maven/xdocs/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb2/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb2/beaworkshop/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb2/conf/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb2/dao/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb2/sunone/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb3/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/ejb/ejb3/jboss/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/hibernate/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/hibernate/hibernate3/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/mock/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/service/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/spring/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/test/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/web/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/web/struts/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/web/struts/action/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/web/struts/configuration/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/web/struts/form/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/web/struts/jsp/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/webservice/.*
- ./templates/entity_facade_jboss_jsk_2_0/templates/webservice/axis/.*
- ./templates/java5_2_tier/.*
- ./templates/java5_2_tier/conf/.*
- ./templates/java5_2_tier/conf/conf-general/.*
- ./templates/java5_2_tier/conf/conf-general/jmeter/.*
- ./templates/java5_2_tier/templates/.*
- ./templates/java5_2_tier/templates/config/.*
- ./templates/java5_2_tier/templates/config/ant/.*
- ./templates/java5_2_tier/templates/config/ear/.*
- ./templates/java5_2_tier/templates/config/intellij/.*
- ./templates/java5_2_tier/templates/config/jboss/.*
- ./templates/java5_2_tier/templates/config/jmeter/.*
- ./templates/java5_2_tier/templates/config/maven/.*
- ./templates/java5_2_tier/templates/config/maven/xdocs/.*
- ./templates/java5_2_tier/templates/docbook/.*
- ./templates/java5_2_tier/templates/hibernate/.*
- ./templates/java5_2_tier/templates/hibernate/hibernate3/.*
- ./templates/java5_2_tier/templates/service/.*
- ./templates/java5_2_tier/templates/service/log/.*
- ./templates/java5_2_tier/templates/spring/.*
- ./templates/java5_2_tier/templates/test/.*
- ./templates/java5_2_tier/templates/web/.*
- ./templates/java5_2_tier/templates/web/configuration/.*
- ./templates/java5_2_tier/templates/web/jasperreports/.*
- ./templates/java5_2_tier/templates/web/rss/.*
- ./templates/java5_2_tier/templates/web/security/.*
- ./templates/java5_2_tier/templates/web/security/acegi/.*
- ./templates/java5_2_tier/templates/web/struts/.*
- ./templates/java5_2_tier/templates/web/struts/action/.*
- ./templates/java5_2_tier/templates/web/struts/configuration/.*
- ./templates/java5_2_tier/templates/web/struts/form/.*
- ./templates/java5_2_tier/templates/web/struts/inc/.*
- ./templates/java5_2_tier/templates/web/struts/jsp/.*
- ./templates/java5_2_tier/templates/web/struts/login/.*
- ./templates/java5_2_tier/templates/web/struts/upload/.*
- ./templates/java5_2_tier/templates/web/struts/web-inf/.*
- ./templates/java5_2_tier/templates/web/struts/web-inf/classes/.*
- ./templates/java5_2_tier/templates/web/tapestry/.*
- ./templates/java5_2_tier/templates/web/tapestry/config/.*
- ./templates/java5_2_tier/templates/web/tapestry/html/.*
- ./templates/java5_2_tier/templates/web/tapestry/inc/.*
- ./templates/java5_2_tier/templates/web/tapestry/java/.*
- ./templates/java5_2_tier/templates/web/tapestry/java/component/.*
- ./templates/java5_2_tier/templates/web/tapestry/java/core/.*
- ./templates/java5_2_tier/templates/web/tapestry/java/valid/.*
- ./templates/java5_2_tier/templates/web/tapestry/login/.*
- ./templates/java5_2_tier/templates/webservice/.*
- ./templates/java5_2_tier/templates/webservice/axis/.*
- ./templates/java5_2_tier/templates/webservice/xfire/.*
